version: '3.9'

services:
  aesm:
    image: initc3/linux-sgx:2.13-ubuntu20.04
    devices:
      - /dev/isgx
    volumes:
      - aesmd-socket:/var/run/aesmd
      #- ./aesmd.conf:/etc/aesmd.conf
    user: aesmd
    #stdin_open: true
    #tty: true
    working_dir: /opt/intel/sgx-aesm-service/aesm
    environment:
      LD_LIBRARY_PATH: /opt/intel/sgx-aesm-service/aesm
    command: ./aesm_service --no-daemon

  sgxiot:
    image: sgx_iot
    build:
      context: .
      dockerfile: Dockerfile
      #args:
      #  SGX_MODE: hw
      #  SGX_DEBUG: 0
    depends_on:
      - aesm
    devices:
      - /dev/isgx
    environment:
      SGX_SPID: ${SGX_SPID}
      IAS_PRIMARY_KEY: ${IAS_PRIMARY_KEY}
      PYTHONBREAKPOINT: ipdb.set_trace
      SGX_DEBUG: 1
    volumes:
      - aesmd-socket:/var/run/aesmd
      #- ./common:/home/photon/sgxiot/common
      #- ./demo_sgx:/home/photon/sgxiot/demo_sgx
      #- ./.auditee.yml:/home/photon/sgxiot/.auditee.yml
      #- ./default.nix:/home/photon/sgxiot/default.nix
      #- ./makefile:/home/photon/sgxiot/makefile
      #- ./verify.py:/home/photon/sgxiot/verify.py
      #- ./run_keygen.sh:/home/photon/sgxiot/run_keygen.sh
      #- ./run_quote.sh:/home/photon/sgxiot/run_quote.sh
      - ./run_demo_sgxra.sh:/home/photon/sgxiot/run_demo_sgxra.sh
      - /var/run/docker.sock:/var/run/docker.sock
    command: ./run_demo_sgxra.sh

volumes:
  aesmd-socket:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
      o: "rw"
